// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFfVE3uyVniouwp_66XE2k9bu8vTUdtG8',
    appId: '1:350287245353:web:0179870c998d1f6b742c38',
    messagingSenderId: '350287245353',
    projectId: 'aplikasi-absensi-sd',
    authDomain: 'aplikasi-absensi-sd.firebaseapp.com',
    databaseURL: 'https://aplikasi-absensi-sd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-absensi-sd.firebasestorage.app',
    measurementId: 'G-YNZF1R70SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_NYLBxWn4yyeo7pJppTA67Vhb5odrbL8',
    appId: '1:350287245353:android:f000ec4d00bb2745742c38',
    messagingSenderId: '350287245353',
    projectId: 'aplikasi-absensi-sd',
    databaseURL: 'https://aplikasi-absensi-sd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-absensi-sd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHlFgTMK3qelV36p7gWvgxBoBzGnza6mw',
    appId: '1:350287245353:ios:c8ec2b809ca67578742c38',
    messagingSenderId: '350287245353',
    projectId: 'aplikasi-absensi-sd',
    databaseURL: 'https://aplikasi-absensi-sd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-absensi-sd.firebasestorage.app',
    iosBundleId: 'com.example.absensiSekolah',
  );

}